### ISSUE TITLE
Prototype using harp for markdown docs

### ISSUE THREAD

**Issue by spinscale** [claudiajs/claudiajs.com#1]
I created tiny small prototype using the milligram CSS framework, that uses the markdown docs for create a static website using harp.. so it could be uploaded to S3. Guess you might have planned anything else, but maybe this helps you...

the repo and some help to get up and running is at https://github.com/spinscale/claudiajs-docs

**Comment by gojko** [comment]
thanks, this is a holding repo for assets, I don't have time to work on a website yet.
